# Generated by Django 4.1.1 on 2022-10-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_typeof_building_typeof"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"ordering": ["-created"]},
        ),
        migrations.CreateModel(
            name="HandPicked",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.building"
                    ),
                ),
            ],
        ),
    ]
