# Generated by Django 4.1.1 on 2022-10-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_building_options_handpicked"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HandPicked",
            new_name="HandPick",
        ),
        migrations.AlterModelOptions(
            name="handpick",
            options={"ordering": ["-created"]},
        ),
    ]
