# Generated by Django 4.1.1 on 2022-11-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_chat_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="reply_pending",
            field=models.BooleanField(default=False),
        ),
    ]
